import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    form: {
        flex: 1,
        backgroundColor: '#fff',
        alignItems: 'center',
        paddingTop: 10,
        width: '100%',
    },
    label: {
        fontSize: 16,
        width:'100%',
        marginBottom: 20,
        textAlign: 'center',
        alignSelf: 'center',
    },
    headerLabel: {
        fontSize: 30,
        width:'100%',
        paddingHorizontal: 50,
        marginBottom: 20,
        marginTop: 10,
        textAlign: 'center',
    },
    newContactLabel: {
        fontSize: 16,
        marginBottom: 18,
        textAlign: 'center',
        alignSelf: 'center',
    },
    contactList: {
        flexDirection: 'column',
        width: '100%',
        paddingVertical: 12,
        paddingHorizontal: 12,
        borderRadius: 4,
        elevation: 3,
        backgroundColor: 'rgb(245, 245, 245)',
        marginBottom: 10,
    },
    newContactContainer: {
        paddingVertical: 20,
        marginBottom: 50,
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '80%',
        alignItems: 'center',
    },
    editContactContainer: {
        flexDirection: 'column',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 10,
    },
    contactContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 7,
    },
    contactTextContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '60%',
      },
    contactIconContainer: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        paddingHorizontal: 10,
        width: '30%',
    },
    contactText: {
        fontSize: 16,
        fontStyle: 'italic',
        fontWeight: 'bold',
        color: 'rgb(128, 0, 128)',
        marginRight: 10,
    },
    contactIcon: {
        marginLeft: 10,
    },
    textInput: {
        borderColor: '#000',
        borderWidth: 1,
        backgroundColor: '#ccc',
        marginBottom: 15,
        paddingVertical: 4,
        paddingHorizontal: 52,
        textAlign: 'center',
    },
    emergencyTextInput: {
        borderColor: '#000',
        borderWidth: 0.5,
        backgroundColor: '#ccc',
        marginBottom: 5,
        paddingVertical: 4,
        width: '70%',
        textAlign: 'center',
    },
    newContactInput: {
        borderColor: '#ccc',
        borderWidth: 1,
        marginBottom: 15,
        paddingVertical: 4,
        paddingHorizontal: 12,
    },
    emergencyContainer: {
        paddingVertical: 20,
        flexDirection: 'column',
        justifyContent: 'center',
        width: '90%',
        alignItems: 'center',
    },
    buttonContainer: {
      paddingVertical: 30,
      flexDirection: 'column',
      justifyContent: 'center',
      elevation: 3,
      marginTop: 10,
      width: '60%',
    },
    emergencyButton: {
        flexDirection: 'row',
    },

    button: {
        width: '60%',
        alignItems: 'center',
        paddingVertical: 12,
        paddingHorizontal: 32,
        borderRadius: 4,
        elevation: 3,
        backgroundColor: 'black',
        marginBottom: 10,
        marginTop: 10,
    },
    addButton: {   
        width: '100%',
        alignItems: 'center',
        paddingVertical: 6,
        paddingHorizontal: 12,
        borderRadius: 4,
        elevation: 3,
        backgroundColor: 'green',
        marginBottom: 10,
    },

    emergencyButtonContainer: {
        flexDirection: 'column',
        width: '90%',
        alignItems: 'center',
        paddingVertical: 12,
        paddingHorizontal: 12,
        borderRadius: 4,
        elevation: 3,
        backgroundColor: 'red',
        marginBottom: 10,
    },

    registerButton: {
        width: '100%',
        alignItems: 'center',
        paddingVertical: 12,
        paddingHorizontal: 50,
        borderRadius: 4,
        elevation: 3,
        backgroundColor: 'blue',
        marginBottom: 10,
    },
    signOutButtonContainer: { 
        flexDirection: 'row',
        justifyContent: 'flex-end',
        paddingHorizontal: 5,
        marginTop: 10,
        marginBottom: 5,
        width: '100%',
    },
    signOutButton: {
        paddingVertical: 7,
        paddingHorizontal: 10,
        alignItems: 'center',
        borderRadius: 4,
        elevation: 3,
        //backgroundColor: 'black',
        backgroundColor: 'rgb(245, 245, 245)',
        marginBottom: 0,
    },
    text: {
        fontSize: 16,
        lineHeight: 21,
        fontWeight: 'bold',
        letterSpacing: 0.25,
        color: 'white',
    },
    signOutText: {
        fontSize: 16,
        lineHeight: 21,
        letterSpacing: 0.25,
        color: 'black',
    },
      emergencyText: {
        fontSize: 16,
        lineHeight: 21,
        fontWeight: 'bold',
        letterSpacing: 0.25,
        color: 'white',
      },
});